require 'spec_helper'

describe 'First Lab:' do
  it 'you made a change' do
    new_file_made = Dir["*"].size > 5
    file_edited = !File.read("./edit-me.txt").empty?
    expect((new_file_made || file_edited)).to be_truthy, "Make sure you have added a new file or edited edit-me.txt"
    are changes made here?
  end
end
Adding changes...                                                               
Committing changes...                                                           
It looks like you have no changes to commit. Will still try updating your submis
sion...                                                                         
Pushing changes to GitHub...                                                    
Submitting lesson...                                                            
Done.                                                                           
[11:18:37] (master) first-lab-ruby-learn-cli-ile-q-000                          
// ♥ learn submit                                                               
Adding changes...                                                               
Committing changes...                                                           
It looks like you have no changes to commit. Will still try updating your submis
sion...                                                                         
Pushing changes to GitHub...                        
